name: nas_note
description: A Flutter package for secure note-taking with SQLite storage and CRUD operations.
version: 0.0.1
homepage: https://github.com/n-nourdine/nas_note
repository: https://github.com/n-nourdine/nas_note
issue_tracker: https://github.com/nourdine/nas_note/issues

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
